config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get '/user_profile' => "users#user_profile"

  get '/' => "menu_boards#home"

  get 'home' => 'menu_boards#home'
  root :to => 'menu_boards#home'
  get 'help' => 'menu_boards#help'
  get 'about' => 'menu_boards#about'
  get '/pricing' => 'menu_boards#pricing'
  get 'contact' => 'menu_boards#contact'
  post "/mail_contact"  => 'menu_boards#contact_us'
  get "/index"  => 'menu_boards#index'
  get 'signup' => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'search_page'   => 'users#search'
  get 'dish_edit' => 'dishes#edit'
  post 'dish_new' =>  'dishes#new'
  get  'dish_new' =>  'dishes#new'
  get 'dish_show' => 'dishes#show'
  get 'category_search' => 'users#category_search'

  patch "/dishes/:id" => 'dishes#edit'

  post "category_edit_save" => 'menu_boards#update'

  get 'info_edit'  => 'users#info_edit'

  get 'category_new' =>  'categories#new'
  delete '/categories/:id' => 'categories#destroy'

  resource  :menu
  resources :categories,          only: [:create, :destroy, :edit]
  resources :dishes,              only: [:create, :destroy, :edit]
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  #A create action for password resets.
  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash.now[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash.now[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<!--Updating the errors for password resets.-->
<% provide(:title, 'Reset password') %>

<html class="wow-animation" lang="en">
  <head>
    <title>A Visual Menu</title>
    <!--<link rel="icon" href="/assets/favicon.ico" type="image/x-icon">-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,700,900">
  </head>
  <body style='padding-top: 0;'>
  <p class='header-brand'><%= image_tag '/assets/logo.png', width: 200, height: 150, alt: 'logo'%></p>
    <div class='login-page'>
      <section class="login-card">
        <a href='/'>
          <div class='login-exit'>
            <div></div>
            <div></div>
          </div>
        </a>
        <p class="login-logo">O͞O</p>
        <header class="login-header">Reset Password</header>
        <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= hidden_field_tag :email, @user.email %>

          <div class="form-component-c">
            <%= f.password_field :password, class: 'form-component fc-small', placeholder: "Password", required: true %>
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
          </div>
          <div class="form-component-c">
            <%= f.password_field :password_confirmation, class: 'form-component fc-small', placeholder: "Confirm password", required: true %>
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
          </div>

          <div class="form-component-c fc-active btn-animation">
            <%= f.submit "Submit", class: "fc-hide", id: 'send' %>
            <label class='form-component fc-small fc-point' for="send">
              Submit
              <%= render :partial => "shared/form_icon", :locals => {:icon => 'send'} %>
            </label>
          </div>
        <% end %>

      </section>
    </div>
    <%# render 'layouts/footer' %>
  </body>
</html>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<html class="wow-animation" lang="en">
  <head>
    <title>A Visual Menu</title>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,700,900">
  </head>
  <body style='padding-top: 0;'>
    <div style="padding: 50px 0; display: flex; align-items: center; justify-content: center;">
  </div>
    <div class='login-page'>
      <section class="login-card">
        <a href='/login'>
          <div class='login-exit'>
            <div></div>
            <div></div>
          </div>
        </a>
        <%= image_tag '/assets/avisualmenu-bold-logo.svg', height: 50, alt: 'logo', style: "padding: 20px 0;"%>
        <header class="login-header">Forgot Password</header>
        <%= form_for(:password_reset, url: password_resets_path) do |f| %>
            <div class="form-errors">
              <% flash.each do |message_type, message| %>
                <p class="alert-<%= message_type %>"><%= message %></p>
              <% end %>
            </div>
            <div class="form-component-c">
              <%= f.email_field :email, class: 'form-component fc-small', required: true, placeholder: "email" %>
              <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
            </div>
            <div class="form-component-c fc-active btn-animation">
              <%= f.submit "Submit", class: "fc-hide", id: 'send' %>
              <label class='form-component fc-small fc-point' for="send">
                Submit
                <%= render :partial => "shared/form_icon", :locals => {:icon => 'send'} %>
              </label>
            </div>
            <p class="signup-component"><a href="/login">Sign in</a></p>
        <% end %>
      </section>
    </div>
    <%# render 'layouts/footer' %>
  </body>
</html>