config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get '/user_profile' => "users#user_profile"

  get '/' => "menu_boards#home"

  get 'home' => 'menu_boards#home'
  root :to => 'menu_boards#home'
  get 'help' => 'menu_boards#help'
  get 'about' => 'menu_boards#about'
  get '/pricing' => 'menu_boards#pricing'
  get 'contact' => 'menu_boards#contact'
  post "/mail_contact"  => 'menu_boards#contact_us'
  get "/index"  => 'menu_boards#index'
  get 'signup' => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'search_page'   => 'users#search'
  get 'dish_edit' => 'dishes#edit'
  post 'dish_new' =>  'dishes#new'
  get  'dish_new' =>  'dishes#new'
  get 'dish_show' => 'dishes#show'
  get 'category_search' => 'users#category_search'

  patch "/dishes/:id" => 'dishes#edit'

  post "category_edit_save" => 'menu_boards#update'

  get 'info_edit'  => 'users#info_edit'

  get 'category_new' =>  'categories#new'
  delete '/categories/:id' => 'categories#destroy'

  resource  :menu
  resources :categories,          only: [:create, :destroy, :edit]
  resources :dishes,              only: [:create, :destroy, :edit]
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/shared/_category_select_search.html.erb
<div class="category-select">
  <%= form_tag(category_search_path, :method => "get", class: 'navbar-form navbar-left', id: 'form') do %>
    <%= hidden_field_tag :user_id, @user.id %>
    <div class="input-group form-component-c fc-max-content">
      <%= select_tag("category[title]",options_from_collection_for_select(@categories, "category", "category"),
            prompt: "Categories", :onchange => "submit_func()", :id => "selectedCategory", :class => "form-component fc-small") %>
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'expand_more'} %>
    </div>
  <% end %>
</div>


<script type="text/javascript">
  function submit_func() {
    var selectedCategory = document.getElementById("selectedCategory").value;
    var form = document.getElementById("form");
    if( selectedCategory !== "" ){
      form.submit();
    }
  }
</script>

app/views/shared/_create_category.html.erb
<div class='create-category-wrapper'>
    <h3>Create a Category</h3>
    <%= form_for(@micropost, html: { multipart: true }) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.label :priority %><br>
          <%= f.number_field :priority, required: true %>
        </div>
        <div class="field form-component-c">
            <%= f.text_field :content, placeholder: "Category Name", class: "form-component fc-small"  %>
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
        </div>
        <div class="field form-component-c fc-active ">
            <%= f.submit "Post", class: 'fc-hide', id: 'send' %>
            <label class='form-component fc-small fc-point' for="send">
            Submit
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'send'} %>
            </label>
        </div>
    <% end %>
</div>

app/views/shared/_dish_modal.html.erb
<div id='micropost-modal' class="micropost-modal">
<div onclick='closeModal()' class='mpm-close-bg'></div>
<% if logged_in? %>
  <div class='micropost-modal-c'>
<% else %>
  <div class='micropost-modal-c no-top'>
<% end %>
  <div class='mpm-img-c'>
    <%= image_tag "", id: "mpm-image" %>
    </div>
    <div class='mpm-details'>
      <p id="mpm-price" class='mpm-price'></p>
      <p id="mpm-title"></p>
      <p id='mpm-description' class='mpm-description'></p>
    </div>
  </div>
</div>
<script type='text/javascript'>
let a = [];
function closeModal(props) {
    document.getElementById('micropost-modal').classList.remove('active')
  }
</script>

app/views/shared/_edit_dish_form.html.erb
<!--The form partial for creating menu item on the home.html.erb file-->
<div class="micropost-form-container">
  <%= render 'shared/back_to_top' %>
  <div class='delete-micropost'>
    <%= link_to(@dish, method: :delete, data: { confirm: "Delete Category dish?" }, class: 'delete-micropost-btn') do %>
      <span class='material-icons'>delete</span>Remove
    <% end %>
  </div>
  <%= form_for(@dish, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class='form-component-pic-width'>
      <span class="picture form-component-c">
        <%= f.file_field :picture, class: 'fc-hide', id: 'file', accept: 'image/jpeg,image/gif,image/png' %>
        <label class='form-component fc-small fc-point' for="file">
        <% if @dish.picture.present? %>
          <img id='post-image' src= <%= @dish.picture %>>
        <% else %>
          <img id='post-image' src='/assets/upload_image.png'>
        <% end %>
        </label>
      </span>
    </div>
    <div class="field form-component-c">
      <%= f.text_field :name, placeholder: "Menu item title...", required: true, class: "form-component fc-small"  %>
      <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
    </div>
    <div class="field form-component-c">
      <div class="categories_select">
        <div class="select">
          <%= select_tag("category", options_from_collection_for_select(@categories, "id", "name"),
              :id => "categories_select") %>
        </div>
      </div>
   </div>
    <div class="field form-component-c">
      <%= f.text_field :price, placeholder: "Menu item price...", required: true, class: "form-component fc-small" %>
      <%= render :partial => "shared/form_icon", :locals => {:icon => 'attach_money'} %>
    </div>
    <div class="field form-component-c fc-big">
      <%= f.text_area :description, placeholder: "Menu item description...", required: true, rows: "3", class: "form-component fc-big" %>
      <%= render :partial => "shared/form_icon", :locals => {:icon => 'notes'} %>
    </div>
    <%= hidden_field_tag :category_id, @category_id %>
    <div class="field form-component-c fc-active ">
      <%= f.submit "Post", class: 'fc-hide', id: 'send' %>
      <label class='form-component fc-small fc-point' for="send">
        Submit
        <%= render :partial => "shared/form_icon", :locals => {:icon => 'send'} %>
      </label>
    </div>
  <% end %>

  <!--Checking the file size with jQuery.-->
  <script type="text/javascript">
    $('.fc-hide').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }else {
        var output = document.getElementById('post-image');
        output.src = URL.createObjectURL(event.target.files[0]);
      }

    });
  </script>
</div>

app/views/shared/_form_icon.html.erb
<!--Displays icon on input.-->
<div class="form-component-btn-c">
    <i class="material-icons form-component-btn fcb-small"><%= icon %></i>
</div>

app/views/shared/_google_analytics_script.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-133825583-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-133825583-1');
</script>

app/views/shared/_identify_users_script.html.erb
<% if Rails.env.production? %>
  <script>
    // This is an example script - don't forget to change it!
    $.get('/user_profile', function(result){
      FS.identify(result.id, {
        displayName: result.name,
        email: result.email,
        reviewsWritten_int: 14,
      });
    });
  </script>
<% end %>

app/views/shared/_micropost_form.html.erb
<!--The form partial for creating menu item on the home.html.erb file-->
<div class="micropost-form-container">
<%= render 'shared/back_to_top' %>
  <%= form_for(@micropost, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <span class="picture form-component-c">
      <%= f.file_field :picture, class: 'fc-hide', id: 'file', accept: 'image/jpeg,image/gif,image/png' %>
      <label class='form-component fc-small fc-point' for="file">
      <% if @micropost.picture.present? %>
        <img id='post-image' src= <%= @micropost.picture %>>
      <% else %>
        <img id='post-image' src='/assets/upload_image.png'>
      <% end %>
      </label>
    </span>
    <div class="field form-component-c">
      <%= f.text_field :content, placeholder: "Menu item title...", class: "form-component fc-small"  %>
      <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
    </div>
    <div class="field form-component-c">
      <%= f.select(:category, options_for_select(@categories_select, :selected => f.object.category), {:prompt => "Select Category"}, :class => "form-component fc-small fc-point") %>
      <%= render :partial => "shared/form_icon", :locals => {:icon => 'expand_more'} %>
    </div>
    <div class="field form-component-c">
      <%= f.text_field :price, placeholder: "Menu item price...", class: "form-component fc-small" %>
      <%= render :partial => "shared/form_icon", :locals => {:icon => 'attach_money'} %>
    </div>
    <div class="field form-component-c fc-big">
      <%= f.text_area :description, placeholder: "Menu item description...", rows: "8", class: "form-component fc-big" %>
      <%= render :partial => "shared/form_icon", :locals => {:icon => 'notes'} %>
    </div>
    <div class="field form-component-c fc-active ">
      <%= f.submit "Post", class: 'fc-hide', id: 'send' %>
      <label class='form-component fc-small fc-point' for="send">
        Submit
        <%= render :partial => "shared/form_icon", :locals => {:icon => 'send'} %>
      </label>
    </div>
  <% end %>

  <!--Checking the file size with jQuery.-->
  <script type="text/javascript">
    $('.fc-hide').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }else {
        var output = document.getElementById('post-image');
        output.src = URL.createObjectURL(event.target.files[0]);
      }

    });
  </script>
</div>

app/views/shared/_pricing_box_item.html.erb
<!--Displays pricing item on pricing box in pricing page.-->
<div class='pricing-box-item'>
    <i class="material-icons pricing-box-item-icon"><%= icon %></i>
    <p class='pricing-box-item-text'><%= text %></p>
</div>

app/views/shared/_search_fab.html.erb
<div class="search-modal non-mobile">
    <button id='search-modal-fab' onclick="showSearchModal()">
        <span class="material-icons">search</span>
    </button>
    <div id='search-modal' class='search-modal-c'>
        <div onclick='hideSearchModal()' id='close-search-modal'></div>
        <div class='search-modal-card'>
            <div class="search-option">
                <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>
                    <%= hidden_field_tag :user_id, @user.id %>
                    <div class="input-group form-component-c">
                        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-component fc-small" %>
                        <% if @category %>
                        <%= hidden_field_tag :category, @category %>
                        <% end %>
                        <div class="form-component-btn-c">
                            <%= button_tag "search", :class => 'material-icons category-search form-component-btn fcb-small fcb-hover', :name => nil %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<script type='text/javascript'>
    function showSearchModal() {
        document.getElementById('search-modal')
        .classList.add('active')
    };
    function hideSearchModal() {
         document.getElementById('search-modal')
        .classList.remove('active');
    }
</script>

app/views/shared/_search_option.html.erb
<div class="search-option non-mobile">
  <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>
    <%= hidden_field_tag :user_id, @user.id %>
    <div class="input-group form-component-c">
      <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-component fc-small" %>
      <% if @category %>
        <%= hidden_field_tag :category, @category %>
      <% end %>
      <div class="form-component-btn-c">
        <%= button_tag "search", :class => 'material-icons category-search form-component-btn fcb-small fcb-hover', :name => nil %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<!--A partial for displaying follower stats.-->
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_address_form.html.erb
<%= form_for(@user, html: { class: "text-left offset-top-30"}) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<fieldset>
			<!-- Address form -->

			<!-- Business-name input-->
			<div class="control-group">
					<label class="control-label">Business Name</label>
					<div class="controls">
							<%= f.text_field :name, class: 'form-control' %>
					</div>
			</div>
			<!-- Business-email-field input-->
			<div class="control-group">
					<label class="control-label">Business Email</label>
					<div class="controls">
							<%= f.email_field :email, class: 'form-control' %>
							<p class="help-block"></p>
					</div>
			</div>

			<!-- Business-phone-field input-->
			<div class="control-group">
					<label class="control-label">Business Phone</label>
					<div class="controls">
							<%= f.text_field :phone, class: 'form-control' %>
							<p class="help-block"></p>
					</div>
			</div>

			<!-- Password-field input-->
			<div class="control-group">
					<label class="control-label">Password</label>
					<div class="controls">
							<%= f.password_field :password, class: 'form-control' %>
							<p class="help-block"></p>
					</div>
			</div>
			<!-- Password confirmation input-->
			<div class="control-group">
					<label class="control-label">Re-enter password</label>
					<div class="controls">
							<%= f.password_field :password_confirmation, class: 'form-control' %>
					</div>
			</div>


			<!-- address-line1 input-->
			<div class="control-group">
					<label class="control-label">Address Line 1</label>
					<div class="controls">
							<%= f.text_field :address_line1, class: 'form-control' %>
							<p class="help-block">Street address, P.O. box, company name, c/o</p>
					</div>
			</div>
			<!-- address-line2 input-->
			<div class="control-group">
					<label class="control-label">Address Line 2</label>
					<div class="controls">
							<%= f.text_field :address_line2, class: 'form-control' %>
							<p class="help-block">Apartment, suite , unit, building, floor, etc.</p>
					</div>
			</div>
			<!-- city input-->
			<div class="control-group">
					<label class="control-label">City / Town</label>
					<div class="controls">
							<%= f.text_field :city, class: 'form-control' %>
							<p class="help-block"></p>
					</div>
			</div>
			<!-- region input-->
			<div class="control-group">
					<label class="control-label">State / Province / Region</label>
					<div class="controls">
							<%= f.text_field :region, class: 'form-control' %>
							<p class="help-block"></p>
					</div>
			</div>
			<!-- postal-code input-->
			<div class="control-group">
					<label class="control-label">Zip / Postal Code</label>
					<div class="controls">
						<%= f.text_field :postal_code, class: 'form-control' %>
							<p class="help-block"></p>
					</div>
			</div>
			<!-- country select -->
			<div class="control-group category-select-form">
					<label class="control-label">Country</label>
					<div class="controls">
						<%= f.select(:country, options_for_select(@countries, :selected => f.object.country), {:prompt => "please select a country"}, style: 'height: 40px;') %>
					</div>
			</div>

			<%= f.submit "Submit", class: "btn btn-primary" %>
	</fieldset>

<% end %>

app/views/shared/_user_not_found_error.html.erb
<div class='error-404'>
  <p class='e4-title'><span>VISUAL</span> MENU</p>
  <% flash.each do |message_type, message| %>
      <p class='e4-error'><%= message %></p>
  <% end %>
  <h1>Sorry, but page was not found</h1>
  <h2>404</h2>
  <p class='e4-message'>You may have mistyped the address or the page may have moved.</p>
  <div class='e4-button-c'>
    <a href="/index">back to home</a>
    <a href="mailto:abunawose@avisualmenu.com">Contact us</a>
  </div>
</div>
<!-- Global RD Mailform Output -->
<div class="snackbars" id="form-output-global"></div>