config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get '/user_profile' => "users#user_profile"

  get '/' => "menu_boards#home"

  get 'home' => 'menu_boards#home'
  root :to => 'menu_boards#home'
  get 'help' => 'menu_boards#help'
  get 'about' => 'menu_boards#about'
  get '/pricing' => 'menu_boards#pricing'
  get 'contact' => 'menu_boards#contact'
  post "/mail_contact"  => 'menu_boards#contact_us'
  get "/index"  => 'menu_boards#index'
  get 'signup' => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'search_page'   => 'users#search'
  get 'dish_edit' => 'dishes#edit'
  post 'dish_new' =>  'dishes#new'
  get  'dish_new' =>  'dishes#new'
  get 'dish_show' => 'dishes#show'
  get 'category_search' => 'users#category_search'

  patch "/dishes/:id" => 'dishes#edit'

  post "category_edit_save" => 'menu_boards#update'

  get 'info_edit'  => 'users#info_edit'

  get 'category_new' =>  'categories#new'
  delete '/categories/:id' => 'categories#destroy'

  resource  :menu
  resources :categories,          only: [:create, :destroy, :edit]
  resources :dishes,              only: [:create, :destroy, :edit]
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :menu
  has_many   :dishes, dependent: :destroy

  validates  :name, presence: true

  before_save :update_priority



  private

    def update_priority
      self.priority = 0 if self.priority.eql?(nil)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    #if current_user
      #@categories = Category.where(:user_id => current_user.id)
    #else
    redirect_to root_url
    #end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    #if current_user
      #@user = current_user
    #else
    redirect_to root_url
    #end
  end

  # GET /categories/new
  def new
    #if current_user
      #@user = current_user
      #@category = Category.new
    #else
    redirect_to root_url
    #end
  end

  # GET /categories/1/edit
  def edit
    #if current_user
      #@user = current_user
      #@category = Category.find(params["id"])
      #@selected_category = @category.name
    #else
    redirect_to root_url
    #end
  end

  # POST /categories
  # POST /categories.json
  def create
    result = _create_and_add_category_to_menu category_params
    #respond_to do |format|
    if result.eql?(true)
      #format.html { redirect_to @category, notice: 'Category was successfully created.' }
      #format.json { render :show, status: :created, location: @category }
      flash[:success] = "Category was successfully created."
      redirect_to root_url
    else
      #format.html { render :new }
      #format.json { render json: @category.errors, status: :unprocessable_entity }
      flash[:error] = "#{result}"
      redirect_to root_url
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if @category.destroy
      flash[:success] = "Category was successfully destroyed."
      redirect_to root_url
    else 
      flash[:info] = "An error occured while deleting the Category."
      redirect_to root_url
    end
    #respond_to do |format|
      #format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      #format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :priority, :is_published, :user_id)
    end

    def _create_and_add_category_to_menu category_params
      if current_user.menu.categories.create([category_params]).first.save
        return true
      else 
        errors = current_user.menu.categories.create([category_params]).first.errors
        logger.debug errors.messages
        return errors.messages
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_create_form.html.erb
<div class='create-category-wrapper'>
    <h3>Create a Category</h3>
    <%= form_for(@category) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field form-component-c">
            <%= f.text_field :name, required: true, placeholder: "Category Name", class: "form-component fc-small"  %>
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
        </div>
        <%= hidden_field_tag :user_id, @user.id %>
        <div class="field form-component-c fc-active ">
            <%= f.submit "Post", class: 'fc-hide', id: 'send' %>
            <label class='form-component fc-small fc-point' for="send">
            Submit
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'send'} %>
            </label>
        </div>
    <% end %>
</div>

app/views/categories/_form.html.erb
<div class='create-category-wrapper'>
    <%= form_for(@category) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field form-component-c">
            <%= f.text_field :name, required: true, :value => @selected_category, placeholder: "Category Name", class: "form-component fc-small"  %>
            <div class="field">
              <%= f.label :priority %><br>
              <%= f.number_field :priority %>
            </div>
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'edit'} %>
        </div>
        <%= hidden_field_tag :user_id, @user.id %>
        <div class="field form-component-c fc-active ">
            <%= f.submit "Post", class: 'fc-hide', id: 'send' %>
            <label class='form-component fc-small fc-point' for="send">
            Submit
            <%= render :partial => "shared/form_icon", :locals => {:icon => 'send'} %>
            </label>
        </div>
    <% end %>
</div>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Priority</th>
      <th>Is published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.priority %></td>
        <td><%= category.is_published %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @category.priority %>
</p>

<p>
  <strong>Is published:</strong>
  <%= @category.is_published %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>