config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  get '/user_profile' => "users#user_profile"

  get '/' => "menu_boards#home"

  get 'home' => 'menu_boards#home'
  root :to => 'menu_boards#home'
  get 'help' => 'menu_boards#help'
  get 'about' => 'menu_boards#about'
  get '/pricing' => 'menu_boards#pricing'
  get 'contact' => 'menu_boards#contact'
  post "/mail_contact"  => 'menu_boards#contact_us'
  get "/index"  => 'menu_boards#index'
  get 'signup' => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'search_page'   => 'users#search'
  get 'dish_edit' => 'dishes#edit'
  post 'dish_new' =>  'dishes#new'
  get  'dish_new' =>  'dishes#new'
  get 'dish_show' => 'dishes#show'
  get 'category_search' => 'users#category_search'

  patch "/dishes/:id" => 'dishes#edit'

  post "category_edit_save" => 'menu_boards#update'

  get 'info_edit'  => 'users#info_edit'

  get 'category_new' =>  'categories#new'
  delete '/categories/:id' => 'categories#destroy'

  resource  :menu
  resources :categories,          only: [:create, :destroy, :edit]
  resources :dishes,              only: [:create, :destroy, :edit]
  resources :relationships,       only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <span>© 2018, A Visual Menu. All Rights Reserved.</span>
</footer>

app/views/layouts/_head.html.erb
<title>A Visual Menu</title>
<%= favicon_link_tag asset_path('favicon.png') %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
<meta name="title" content="A Visual Menu">
<meta name="keywords" content="menu designs, menu, menu ideas, food menu, visual menu, event planning, food truck menu, Restaurant Menu Templates, Restaurant Menu Designs ">
<meta name="description" content="Enhance your menu with visuals.">
<meta name="google-site-verification" content="fRD1FzHUEveMq-OwTw5cFd8pWRrr-36_JShIY3P1c8w" />
<!-- Favicons -->
<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<% if Rails.env.production? %>
    <%= render 'shared/google_analytics_script' %>
<% end %>

app/views/layouts/_header.html.erb
<nav id="app-navigation" class='app-navigation'>
<div class='app-navigation-close-bg'></div>
<% if logged_in? %>
  <p class='app-navigation-btn'><span id="app-navigation-btn" class='material-icons'>menu</span></p>
  <ul class='app-navigation-list'>
    <li>
      <span class='nav-link'>
        <%= link_to(root_path) do %>
          <span class='material-icons'>dashboard</span>
          Board
        <% end %>
      </span>
    </li>
    <li>
      <span class='nav-link'>
        <%= link_to(current_user) do %>
          <span class='material-icons'>local_dining</span>
          Menu
        <% end %>
      </span>
    </li>
    <li>

      <span class='nav-link'>
        <%= link_to(info_edit_path(:id => current_user.id), {:method => "get"}) do %>
          <span class='material-icons'>edit</span>
          Edit profile
        <% end %>
      </span>
    </li>
    <li>
        <span class='nav-link'>
          <%= link_to(logout_path, {:method => "delete"}) do %>
            <span class='material-icons'>exit_to_app</span>
            Log Out
          <% end %>
        </span>
    </li>
  </ul>
<% else %>
  <%= link_to "Log in", login_path %>
<% end %>
</nav>

  <script>
    window.onclick = function(event) {
      let modal = document.getElementById('app-navigation')
      let isModal =  document.getElementById('app-navigation-btn')
      let userModal = document.getElementById('#user-profile-modal')
    if (event.target == modal || event.target == isModal) {
      modal.classList.add('active')
    } else {
      modal.classList.remove('active')
    }
  }
</script>

app/views/layouts/_script.html.erb
<!-- jQuery -->
<script src="/assets/jquery.min.js"></script>
<script src="/assets/moment.min.js"></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <% if logged_in? %>
      <div>
        <%= render 'layouts/header' %>
      </div>
      <div class="margin-top">
        <%= yield %>
        <%# debug(params) if Rails.env.development? %>
      </div>
    <% else %>
      <div class="no-margin-top">
        <%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    <% end %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/script' %>
  </body>
</html>